name = sns
description = Adds ninja armour and weapons to the game.
author = Scottii
depends = 3d_armor
optional_depends = default,dmobs,waterdragon,mcl_burning,mobs,creatura
title = Shinobi no Satori